spring:
  data:
    mongodb:
      username: admin
      password: pass
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.coder.ecommerce.kafka.OrderConfirmation, paymentConfirmation:com.coder.ecommerce.kafka.PaymentNotificationRequest

  mail:
    host: localhost
    port: 25
    username: admin
    password: admin
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000


server:
  port: 8040
